apiVersion: apps/v1
kind: Deployment
metadata:
   name: registry
   labels: 
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeName: controlplane
      containers:
        - name: registry
          image: registry:2.8.2
          volumeMounts:
            - name: repo-vol
              mountPath: /var/lib/registry
            - name: certs-vol
              mountPath: /certs
              readOnly: true
            - name: auth-vol
              mountPath: /auth
              readOnly: true
          env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/tls.crt
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"    
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/tls.key

      volumes: 
         - name: repo-vol
           persistentVolumeClaim:
             claimName: registry-pvc
         - name: certs-vol
           secret:
             secretName: certs-secret
         - name: auth-vol
           secret:
             secretName: auth-secret



